import {useEffect,useState} from 'react';
import {count,date,useRuntimeReport,type RuntimeReport} from './RuntimeDashboard';
type Timeline={complete:boolean;truncated:boolean;events:Array<{at:number;kind:string;text:string;rc?:number;provider?:string;request?:number}>};
export function OpenHandsSessions({report:external,error:externalError='',reload:externalReload,view='current'}:{report?:RuntimeReport|null;error?:string;reload?:()=>void;view?:'current'|'recommendations'|'evidence'}){
 const local=useRuntimeReport(external===undefined),report=external===undefined?local.report:external,error=external===undefined?local.error:externalError,reload=externalReload||local.reload;
 const [selected,setSelected]=useState(()=>new URLSearchParams(location.hash.split('?')[1]||'').get('session')||''),[runtime,setRuntime]=useState('all'),[role,setRole]=useState('all'),[model,setModel]=useState('all'),[status,setStatus]=useState('all'),[query,setQuery]=useState(''),[timeline,setTimeline]=useState<Timeline|null>(null),[timelineError,setTimelineError]=useState('');
 const rows=(report?.sessions||[]).filter(s=>(runtime==='all'||(s.runtime||'openhands')===runtime)&&(role==='all'||s.role===role)&&(model==='all'||s.model===model)&&(status==='all'||s.status===status)&&`${s.id} ${s.unit} ${s.role} ${s.model}`.toLowerCase().includes(query.toLowerCase()));
 const session=rows.find(s=>s.id===selected)||rows[0];
 useEffect(()=>{
  setTimeline(null);setTimelineError('');if(!session?.journal_available)return;
  const controller=new AbortController();
  fetch('/api/runtime-journal?id='+encodeURIComponent(session.id),{signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error(`Timeline unavailable (HTTP ${r.status})`);return r.json();}).then(setTimeline).catch(e=>{if(e.name!=='AbortError')setTimelineError(e.message);});
  return()=>controller.abort();
 },[session?.id,session?.journal_available,report?.collected_at]);
 const options=(key:'runtime'|'role'|'model'|'status')=>[...new Set(report?.sessions.map(s=>s[key]||'openhands'))].sort();
 return <section className="runtime-sessions"><h2>Agent sessions and provider evidence</h2><p>OpenHands SDK builders and reviewers, interactive Canvas conversations and real native supervisor jobs keep their own runtime identity.</p>
 <button className="button" onClick={reload}>Reload sessions</button>{error&&<p role="alert">{error} Previously loaded evidence may be stale.</p>}
 <div className="runtime-filters"><label className="field">Runtime<select value={runtime} onChange={e=>setRuntime(e.target.value)}><option value="all">All runtimes</option>{options('runtime').map(r=><option key={r}>{r}</option>)}</select></label>
 <label className="field">Role<select value={role} onChange={e=>setRole(e.target.value)}><option value="all">All roles</option>{options('role').map(r=><option key={r}>{r}</option>)}</select></label>
 <label className="field">Model<select value={model} onChange={e=>setModel(e.target.value)}><option value="all">All models</option>{options('model').map(m=><option key={m}>{m}</option>)}</select></label>
 <label className="field">Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{options('status').map(s=><option key={s}>{s}</option>)}</select></label>
 <label className="field">Find session<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Unit, model, role or run ID"/></label></div>
 <label className="field">Session<select value={session?.id||''} onChange={e=>setSelected(e.target.value)}>{rows.map(s=><option key={s.id} value={s.id}>{date(s.started)} · {s.unit} · {s.role} · {s.model} · {s.status} · {s.id.slice(-8)}</option>)}</select></label>
 {report&&!rows.length&&<p>No retained agent sessions match these filters.</p>}
 {session&&<><h3>{session.unit} · {session.role}</h3><p>{session.runtime||'openhands'} · {session.model} · {session.provider||'Provider not recorded'} · {session.status} · exit {session.rc??'not recorded'}</p>
 <div className="runtime-scroll"><table><tbody>{[['Accounted tokens',count(session.tokens)],['Input tokens',count(session.input)],['Output tokens',count(session.output)],['Cache read tokens',count(session.cached)],['API calls',count(session.requests)],['Usage coverage',session.complete?'Complete':'Partial / unknown'],['Tool calls',count(session.context.tool_calls)],['Tool errors',count(session.context.tool_errors)],['Repeated commands',count(session.context.repeated_commands)],['Tool history coverage',session.context_complete?'Complete':'Partial / unknown']].map(([k,v])=><tr key={k}><th>{k}</th><td>{v}</td></tr>)}</tbody></table></div>
 {session.action&&<p>Typed supervisor decision: {session.action}</p>}{session.session_url&&<a className="button" href={session.session_url} target="_blank" rel="noreferrer">Open full OpenHands conversation viewer</a>}
 {session.skills&&<p>Activated skills: {session.skills.activated.join(', ')||'None reported'} · Invoked skills: {session.skills.invoked.join(', ')||'None reported'}</p>}
 {view==='recommendations'&&<><h3>Optimization evidence</h3><p>{session.context_complete&&session.unused_tools.includes('execute')?'The completed observed run recorded zero Execute calls. Review its schema overhead for this role before changing the runtime.':'Only recorded usage supports conclusions. Missing history does not establish unused tools or instructions.'}</p>{!!session.context.repeated_commands&&<p>Inspect repeated commands in the timeline. Retain necessary verification and measure savings before removing instructions.</p>}<p>Runtime prompt or tool changes require a reviewed source change. Audit snapshots are read-only observations; this page does not silently change active builders.</p></>}
 {session.context_requests.length>0&&<><h3>Recorded request context</h3><p>Approximate SDK context estimates, separate from billed tokens and measured savings.</p><div className="runtime-scroll"><table><thead><tr><th>Request</th><th>Context</th><th>System</th><th>Tool schemas</th></tr></thead><tbody>{session.context_requests.map((r,i)=><tr key={i}><td>{i+1}</td><td>{count(r.estimated_context_tokens)}</td><td>{count(r.estimated_system_tokens)}</td><td>{count(r.estimated_tool_schema_tokens)}</td></tr>)}</tbody></table></div></>}
 <h3>Retained session timeline</h3>{timelineError&&<p role="alert">{timelineError}</p>}{!session.journal_available&&<p>No SDK timeline was retained for this older run or runtime. This does not mean there were no tool calls. Native Codex history and the Canvas viewer remain separate.</p>}
 {timeline&&<><p>Timeline coverage: {timeline.complete?'Complete':'Partial / unknown'}{timeline.truncated?' · bounded retention truncated':''}. Credentials are redacted.</p><ol className="runtime-timeline">{timeline.events.map((e,i)=><li key={i}><strong>{e.kind}</strong> · {date(e.at)}{e.provider&&` · ${e.provider}`}{e.rc!==undefined&&` · exit ${e.rc}`}<pre>{e.text}</pre></li>)}</ol></>}
 </>}
 <p>{report?.evidence} Latest {report?.session_limit} runtime sessions maximum.</p>
 {(view==='evidence'||view==='current')&&<><h3>A6API account calls</h3><p>Collected {date(report?.billing_collected_at)} · {report?.billing_scope}. These include other account callers in this window. Billing calls are not reconstructed agent sessions.</p>
 <div className="runtime-scroll"><table><thead><tr><th>Time</th><th>Model</th><th>Input incl. cache</th><th>Cached</th><th>Output</th><th>Billed USD</th></tr></thead><tbody>{report?.provider_calls.map((c,i)=><tr key={c.request_id||i}><td>{date(c.created_at)}</td><td>{c.model}</td><td>{count(c.input_tokens_including_cache)}</td><td>{count(c.cache_read_tokens)}</td><td>{count(c.output_tokens)}</td><td>{c.billed_usd==null?'Unknown':c.billed_usd.toFixed(6)}</td></tr>)}</tbody></table></div></>}
 </section>;
}
